[template.environment]
NEXT_PUBLIC_MEDUSA_BACKEND_URL="URL of your Medusa Server"
NEXT_PUBLIC_STRIPE_API_KEY="Your Stripe Publishable API Key"
[build]
  command = "export SHARP_IGNORE_GLOBAL_LIBVIPS=1 && npm ci && npm run build"
[build.environment]
  NODE_VERSION = "20"